/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 SkidLoader.gltf -ts
*/

import * as THREE from 'three'
import React, { createRef, useEffect, useMemo, useRef, useState } from 'react'
import { useGLTF, useHelper } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { BoxHelper, Color, Material, Vector3 } from 'three'
import { HexColorPicker } from "react-colorful"

type GLTFResult = GLTF & {
  nodes: {
    BRep_1: THREE.Mesh
    BRep_1_1: THREE.Mesh
    BRep_1_2: THREE.Mesh
    BRep_1_3: THREE.Mesh
    BRep_1_4: THREE.Mesh
    BRep_1_5: THREE.Mesh
    BRep_1_6: THREE.Mesh
    BRep_1_7: THREE.Mesh
    BRep_1_8: THREE.Mesh
    BRep_1_9: THREE.Mesh
    BRep_1_10: THREE.Mesh
    BRep_1_11: THREE.Mesh
    BRep_1_12: THREE.Mesh
    BRep_1_13: THREE.Mesh
    BRep_1_14: THREE.Mesh
    BRep_1_15: THREE.Mesh
    BRep_1_16: THREE.Mesh
    BRep_1_17: THREE.Mesh
    BRep_1_18: THREE.Mesh
    BRep_1_19: THREE.Mesh
    BRep_1_20: THREE.Mesh
    BRep_1_21: THREE.Mesh
    BRep_1_22: THREE.Mesh
    BRep_1_23: THREE.Mesh
    BRep_1_24: THREE.Mesh
    BRep_1_25: THREE.Mesh
    BRep_1_26: THREE.Mesh
    BRep_1_27: THREE.Mesh
    BRep_1_28: THREE.Mesh
    BRep_1_29: THREE.Mesh
    BRep_1_30: THREE.Mesh
    BRep_1_31: THREE.Mesh
    BRep_1_32: THREE.Mesh
    BRep_1_33: THREE.Mesh
    BRep_1_34: THREE.Mesh
    BRep_1_35: THREE.Mesh
    BRep_1_36: THREE.Mesh
    BRep_1_37: THREE.Mesh
    BRep_1_38: THREE.Mesh
    BRep_1_39: THREE.Mesh
    BRep_1_40: THREE.Mesh
    BRep_1_41: THREE.Mesh
    BRep_1_42: THREE.Mesh
    BRep_1_43: THREE.Mesh
    BRep_1_44: THREE.Mesh
    BRep_1_45: THREE.Mesh
    BRep_1_46: THREE.Mesh
    BRep_1_47: THREE.Mesh
    BRep_1_48: THREE.Mesh
    BRep_1_49: THREE.Mesh
    BRep_1_50: THREE.Mesh
    BRep_1_51: THREE.Mesh
    BRep_2: THREE.Mesh
    BRep_3: THREE.Mesh
    BRep_4: THREE.Mesh
    BRep_1_52: THREE.Mesh
    BRep_1_53: THREE.Mesh
    ['<Drive_Roller>-<Fillet2>']: THREE.Mesh
    ['<Front_Roller>-<Boss-Extrude1>']: THREE.Mesh
    ['<Rear_Roller>-<CirPattern1>']: THREE.Mesh
    ['<Bogie_Rollers>-<LPattern12>']: THREE.Mesh
    ['<Bogie_Rollers>-<LPattern11>']: THREE.Mesh
    ['<Bogie_Rollers>-<Mirror1>']: THREE.Mesh
    ['<Bogie_Rollers>-<Revolve1>']: THREE.Mesh
    ['<Bogie_Housing>-<Fillet3>']: THREE.Mesh
    ['<Track_-_Homologous_Rubber>-<Fillet3>']: THREE.Mesh
    BRep_1_54: THREE.Mesh
    BRep_2_1: THREE.Mesh
    BRep_1_55: THREE.Mesh
    BRep_2_2: THREE.Mesh
    BRep_3_1: THREE.Mesh
    BRep_4_1: THREE.Mesh
    BRep_5: THREE.Mesh
    BRep_6: THREE.Mesh
    BRep_7: THREE.Mesh
    BRep_8: THREE.Mesh
    BRep_9: THREE.Mesh
    BRep_10: THREE.Mesh
    BRep_11: THREE.Mesh
    BRep_12: THREE.Mesh
    BRep_13: THREE.Mesh
    BRep_14: THREE.Mesh
    BRep_15: THREE.Mesh
    BRep_16: THREE.Mesh
    BRep_17: THREE.Mesh
    BRep_18: THREE.Mesh
    BRep_19: THREE.Mesh
    BRep_20: THREE.Mesh
    BRep_21: THREE.Mesh
    BRep_22: THREE.Mesh
    BRep_23: THREE.Mesh
    BRep_24: THREE.Mesh
    BRep_25: THREE.Mesh
    BRep_26: THREE.Mesh
    BRep_27: THREE.Mesh
    BRep_28: THREE.Mesh
    BRep_29: THREE.Mesh
    BRep_30: THREE.Mesh
    BRep_31: THREE.Mesh
    BRep_32: THREE.Mesh
    BRep_33: THREE.Mesh
    BRep_34: THREE.Mesh
    BRep_35: THREE.Mesh
    BRep_36: THREE.Mesh
    BRep_37: THREE.Mesh
    BRep_38: THREE.Mesh
    BRep_39: THREE.Mesh
    BRep_40: THREE.Mesh
    BRep_41: THREE.Mesh
    BRep_42: THREE.Mesh
    BRep_43: THREE.Mesh
    BRep_44: THREE.Mesh
    BRep_45: THREE.Mesh
    BRep_46: THREE.Mesh
    BRep_47: THREE.Mesh
    BRep_48: THREE.Mesh
    BRep_49: THREE.Mesh
    BRep_50: THREE.Mesh
    BRep_51: THREE.Mesh
    BRep_52: THREE.Mesh
    BRep_53: THREE.Mesh
    BRep_54: THREE.Mesh
    BRep_1_56: THREE.Mesh
    BRep_1_57: THREE.Mesh
    BRep_2_3: THREE.Mesh
    BRep_1_58: THREE.Mesh
    BRep_1_59: THREE.Mesh
    BRep_1_60: THREE.Mesh
    BRep_2_4: THREE.Mesh
    BRep_1_61: THREE.Mesh
    BRep_2_5: THREE.Mesh
    BRep_1_62: THREE.Mesh
    BRep_2_6: THREE.Mesh
    BRep_3_2: THREE.Mesh
    BRep_1_63: THREE.Mesh
    BRep_1_64: THREE.Mesh
    BRep_2_7: THREE.Mesh
    BRep_3_3: THREE.Mesh
    BRep_4_2: THREE.Mesh
    BRep_5_1: THREE.Mesh
    BRep_6_1: THREE.Mesh
    BRep_7_1: THREE.Mesh
    BRep_1_65: THREE.Mesh
    BRep_1_66: THREE.Mesh
    mesh_100: THREE.Mesh
    mesh_100_1: THREE.Mesh
    mesh_100_2: THREE.Mesh
    mesh_100_3: THREE.Mesh
    mesh_101: THREE.Mesh
    mesh_101_1: THREE.Mesh
    mesh_101_2: THREE.Mesh
    mesh_101_3: THREE.Mesh
    BRep_1_68: THREE.Mesh
    BRep_1_69: THREE.Mesh
    BRep_1_70: THREE.Mesh
    BRep_1_71: THREE.Mesh
    BRep_1_72: THREE.Mesh
    BRep_1_73: THREE.Mesh
    BRep_2_9: THREE.Mesh
    ['<Chassis_-_Lift_Arm_Mounting_Panel>-<Cut-Extrude101>']: THREE.Mesh
    ['<Chassis_-_Main_Side_Panel>-<Fillet5>']: THREE.Mesh
    ['<Chassis_-_Main_Side_Panel>-<Cut-Extrude6>']: THREE.Mesh
    BRep_1_74: THREE.Mesh
    BRep_1_75: THREE.Mesh
    BRep_1_76: THREE.Mesh
    BRep_1_77: THREE.Mesh
    BRep_1_78: THREE.Mesh
    BRep_1_79: THREE.Mesh
    BRep_1_80: THREE.Mesh
    BRep_1_81: THREE.Mesh
    BRep_1_82: THREE.Mesh
    BRep_1_83: THREE.Mesh
    BRep_1_84: THREE.Mesh
    BRep_1_85: THREE.Mesh
    BRep_2_10: THREE.Mesh
    BRep_1_86: THREE.Mesh
    BRep_2_11: THREE.Mesh
    BRep_1_87: THREE.Mesh
    BRep_1_88: THREE.Mesh
    BRep_1_89: THREE.Mesh
    BRep_1_90: THREE.Mesh
    BRep_2_12: THREE.Mesh
    BRep_1_91: THREE.Mesh
    BRep_2_13: THREE.Mesh
    BRep_3_4: THREE.Mesh
    BRep_4_3: THREE.Mesh
    BRep_1_92: THREE.Mesh
    BRep_1_93: THREE.Mesh
    BRep_1_94: THREE.Mesh
    BRep_1_95: THREE.Mesh
    BRep_1_96: THREE.Mesh
    BRep_1_97: THREE.Mesh
    BRep_1_98: THREE.Mesh
    BRep_1_99: THREE.Mesh
    BRep_1_100: THREE.Mesh
    ['<Lift_Arm_-_Base_Frame>-<Cut-Extrude11>']: THREE.Mesh
    ['<Lift_Arm_-_Outer_Frame>-<Fillet6>']: THREE.Mesh
    ['<Rear_Dog_Leg_Linkage>-<Mirror1>']: THREE.Mesh
    ['<Lift_Arm_-_Hydraulic_Cylinder_Attachment_Bracket>-<Mirror2>']: THREE.Mesh
    ['<Lift_Arm_-_Hydraulic_Cylinder_Attachment_Bracket>-<Fillet1>']: THREE.Mesh
    ['<Hydraulic_Cylinder>-<Combine1>']: THREE.Mesh
    ['<Lift_Arm_-_Hydraulic_Cylinder_Saddle>-<Boss-Extrude2>']: THREE.Mesh
    ['<Lift_Arm_-_Inter_Frame>-<Boss-Extrude1>']: THREE.Mesh
    ['<Bucket_Control_-_Hydraulic_Cylinder>-<Cut-Extrude5>']: THREE.Mesh
    ['<Lift_Arm_-_Limit_Linkage_Saddle>-<Fillet5>']: THREE.Mesh
    ['<Hydaulic_Cylinder_-_Mounting_Pin>-<CirPattern1>']: THREE.Mesh
    ['<Rear_Dog_Leg_Linkage_-_Mounting_Bolt>-<CirPattern1>']: THREE.Mesh
    ['<Bucket_Control_-_Hydaulic_Cylinder_Saddle>-<Cut-Extrude21>']: THREE.Mesh
    BRep_1_101: THREE.Mesh
    BRep_1_102: THREE.Mesh
    ['<Lift_Arm_-_Limit_Linkage>-<Chamfer3>']: THREE.Mesh
    ['<Lift_Arm_-_Limit_Linkage>-<Chamfer2>']: THREE.Mesh
    ['<Lift_Arm_-_Limit_Linkage>-<Chamfer1>']: THREE.Mesh
    BRep_1_103: THREE.Mesh
    BRep_2_14: THREE.Mesh
    ['<Main_Lift_Hydraulic_-_Arm_Connection_Pin>-<Mirror1>']: THREE.Mesh
    ['<Main_Lift_Hydraulic_-_Arm_Connection_Pin>-<Revolve1>']: THREE.Mesh
    BRep_1_104: THREE.Mesh
    BRep_1_105: THREE.Mesh
    BRep_1_106: THREE.Mesh
    BRep_2_15: THREE.Mesh
    BRep_3_5: THREE.Mesh
    BRep_4_4: THREE.Mesh
    BRep_5_2: THREE.Mesh
    BRep_6_2: THREE.Mesh
    BRep_7_2: THREE.Mesh
    BRep_8_1: THREE.Mesh
    BRep_9_1: THREE.Mesh
    BRep_10_1: THREE.Mesh
    BRep_11_1: THREE.Mesh
    BRep_12_1: THREE.Mesh
    BRep_13_1: THREE.Mesh
    BRep_14_1: THREE.Mesh
    BRep_1_107: THREE.Mesh
    BRep_1_108: THREE.Mesh
    BRep_1_109: THREE.Mesh
    BRep_1_110: THREE.Mesh
    BRep_1_111: THREE.Mesh
    BRep_1_112: THREE.Mesh
    BRep_1_113: THREE.Mesh
    BRep_1_114: THREE.Mesh
    BRep_2_16: THREE.Mesh
    BRep_3_6: THREE.Mesh
    BRep_1_140: THREE.Mesh
    BRep_1_141: THREE.Mesh
    BRep_1_115: THREE.Mesh
    BRep_2_17: THREE.Mesh
    BRep_1_116: THREE.Mesh
    BRep_1_117: THREE.Mesh
    BRep_1_118: THREE.Mesh
    BRep_1_119: THREE.Mesh
    BRep_1_120: THREE.Mesh
    BRep_2_18: THREE.Mesh
    BRep_3_7: THREE.Mesh
    BRep_4_5: THREE.Mesh
    BRep_1_121: THREE.Mesh
    BRep_2_19: THREE.Mesh
    BRep_1_122: THREE.Mesh
    BRep_1_123: THREE.Mesh
    BRep_2_20: THREE.Mesh
    BRep_1_124: THREE.Mesh
    BRep_1_125: THREE.Mesh
    BRep_1_126: THREE.Mesh
    BRep_1_127: THREE.Mesh
    BRep_1_128: THREE.Mesh
    BRep_1_129: THREE.Mesh
    BRep_1_130: THREE.Mesh
    BRep_2_21: THREE.Mesh
    BRep_1_131: THREE.Mesh
    BRep_2_22: THREE.Mesh
    BRep_3_8: THREE.Mesh
    BRep_4_6: THREE.Mesh
    BRep_5_3: THREE.Mesh
    BRep_6_3: THREE.Mesh
    BRep_7_3: THREE.Mesh
    BRep_8_2: THREE.Mesh
    BRep_9_2: THREE.Mesh
    BRep_1_132: THREE.Mesh
    BRep_2_23: THREE.Mesh
    BRep_1_133: THREE.Mesh
    BRep_1_134: THREE.Mesh
    BRep_1_135: THREE.Mesh
    BRep_1_136: THREE.Mesh
    BRep_1_137: THREE.Mesh
    BRep_2_24: THREE.Mesh
    BRep_1_138: THREE.Mesh
    BRep_1_139: THREE.Mesh
    BRep_2_25: THREE.Mesh
  }
  materials: {
    ['Color #ff0000ff']: THREE.MeshStandardMaterial
    ['Color #808080ff']: THREE.MeshStandardMaterial
    ['Color #c0c0ffff']: THREE.MeshStandardMaterial
    Rubber: THREE.MeshStandardMaterial
    ['Cast Alloy Steel']: THREE.MeshStandardMaterial
    ['Color #cad1eeff']: THREE.MeshStandardMaterial
    ['Color #4c4c4cff']: THREE.MeshStandardMaterial
    ['Color #c0c0c0ff']: THREE.MeshStandardMaterial
    Standard_6: THREE.MeshStandardMaterial
    Standard: THREE.MeshStandardMaterial
    Standard_1: THREE.MeshStandardMaterial
    ['Color #404040ff']: THREE.MeshStandardMaterial
    ['Color #ffff00ff']: THREE.MeshStandardMaterial
    ['Color #ffffffff']: THREE.MeshStandardMaterial
    Standard_2: THREE.MeshStandardMaterial
    Standard_4: THREE.MeshStandardMaterial
    ['AISI 4130 Steel, normalized at 870C']: THREE.MeshStandardMaterial
    Standard_5: THREE.MeshStandardMaterial
    ['Color #fcbc84ff']: THREE.MeshStandardMaterial
    Standard_3: THREE.MeshStandardMaterial
    ['Color #00c0c0ff']: THREE.MeshStandardMaterial
  }
}

export function SkidLoaderModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials, scene } = useGLTF('https://storage.googleapis.com/formacloud-storage-cdn-stg/demo-files/SkidLoader.gltf') as GLTFResult;
  const { userData: { parts, selectedPart, partColors } } = props;
  const [active, setActive] = useState(0);
  const selectedPartRef = useRef();

  const groupRefs = scene && useRef(scene.children.reduce((allRefs, child) => {
    allRefs[child.name] = createRef();
    return allRefs;
  }, {}));

  useHelper(!!selectedPart && groupRefs.current[selectedPart], BoxHelper, 'red')

  const getMaterialColorProps = (groupName, material) => {
    // return material;
    if (selectedPart !== groupName) return material;

    const _mat = material.clone();
    _mat.color = new Color('red');
    return _mat;
  }

  return (
    <group {...props} dispose={null}>
      {parts['Wheels_Assembly-1'] &&
        <group position={[0, 0.35, 0]} scale={0.001} ref={groupRefs.current['Wheels_Assembly-1']}>
          <mesh castShadow receiveShadow geometry={nodes.BRep_1.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Color #ff0000ff']} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_1.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Color #808080ff']} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_2.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Color #c0c0ffff']} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_3.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials.Rubber} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_4.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Color #808080ff']} position={[0, 0, -927.1]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_5.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Color #c0c0ffff']} position={[0, 0, -927.1]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_6.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials.Rubber} position={[0, 0, -927.1]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_7.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Color #ff0000ff']} position={[0, 0, -927.1]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_8.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Color #ff0000ff']} rotation={[0, 0, -Math.PI]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_9.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Color #808080ff']} rotation={[0, 0, -Math.PI]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_10.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials.Rubber} position={[-1041.4, 0, 0]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_11.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Color #808080ff']} position={[0, 0, -927.1]} rotation={[0, 0, -Math.PI]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_12.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials.Rubber} position={[-1041.4, 0, -927.1]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_13.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Color #c0c0ffff']} position={[0, 0, -927.1]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_14.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Color #ff0000ff']} position={[0, 0, -927.1]} rotation={[0, 0, -Math.PI]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_15.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_16.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} rotation={[-Math.PI / 4, 0, 0]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_17.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} rotation={[-Math.PI / 2, 0, 0]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_18.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} rotation={[-2.36, 0, 0]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_19.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} rotation={[-Math.PI, 0, 0]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_20.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} rotation={[2.36, 0, 0]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_21.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} rotation={[Math.PI / 2, 0, 0]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_22.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} rotation={[Math.PI / 4, 0, 0]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_23.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} position={[0, 0, -927.1]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_24.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} position={[0, 0, -927.1]} rotation={[-Math.PI / 4, 0, 0]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_25.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} position={[0, 0, -927.1]} rotation={[-Math.PI / 2, 0, 0]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_26.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} position={[0, 0, -927.1]} rotation={[-2.36, 0, 0]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_27.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} position={[0, 0, -927.1]} rotation={[-Math.PI, 0, 0]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_28.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} position={[0, 0, -927.1]} rotation={[2.36, 0, 0]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_29.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} position={[0, 0, -927.1]} rotation={[Math.PI / 2, 0, 0]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_30.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} position={[0, 0, -927.1]} rotation={[Math.PI / 4, 0, 0]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_31.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Color #c0c0ffff']} rotation={[-Math.PI, 0, -Math.PI]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_32.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_33.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} rotation={[-2.36, 0, -Math.PI]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_34.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} rotation={[-Math.PI, 0, -Math.PI]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_35.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} rotation={[2.36, 0, -Math.PI]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_36.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_37.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} rotation={[Math.PI / 4, 0, Math.PI]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_38.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} rotation={[0, 0, -Math.PI]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_39.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} rotation={[-Math.PI / 4, 0, -Math.PI]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_40.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} position={[0, 0, -927.1]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_41.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} position={[0, 0, -927.1]} rotation={[2.36, 0, -Math.PI]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_42.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} position={[0, 0, -927.1]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_43.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} position={[0, 0, -927.1]} rotation={[-2.36, 0, -Math.PI]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_44.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} position={[0, 0, -927.1]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_45.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} position={[0, 0, -927.1]} rotation={[-Math.PI / 4, 0, -Math.PI]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_46.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} position={[0, 0, -927.1]} rotation={[0, 0, -Math.PI]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_47.geometry} material-color={partColors['Wheels_Assembly-1']} material={materials['Cast Alloy Steel']} position={[0, 0, -927.1]} rotation={[Math.PI / 4, 0, Math.PI]} scale={0.04} />
        </group>}
      {parts['Track_Assembly-1'] &&
        <group position={[0, 0.35, 0]} scale={0.001} ref={groupRefs.current['Track_Assembly-1']}>
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_48.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_49.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_50.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_51.geometry} material={materials['Color #cad1eeff']} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_2.geometry} material={materials['Color #cad1eeff']} position={[0, 0, 203.2]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_3.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_4.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_52.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_53.geometry} material={materials['Color #4c4c4cff']} />
          <mesh castShadow receiveShadow geometry={nodes['<Drive_Roller>-<Fillet2>'].geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes['<Front_Roller>-<Boss-Extrude1>'].geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes['<Rear_Roller>-<CirPattern1>'].geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes['<Bogie_Rollers>-<LPattern12>'].geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes['<Bogie_Rollers>-<LPattern11>'].geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes['<Bogie_Rollers>-<Mirror1>'].geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes['<Bogie_Rollers>-<Revolve1>'].geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes['<Bogie_Housing>-<Fillet3>'].geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes['<Track_-_Homologous_Rubber>-<Fillet3>'].geometry} material={materials['Color #4c4c4cff']} />
        </group>}
      {parts['Chassis_Assembly-1'] &&
        <group position={[0, 0.35, 0]} scale={0.001} ref={groupRefs.current['Chassis_Assembly-1']}>
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_54.geometry} material={materials['Color #c0c0c0ff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_2_1.geometry} material={materials['Color #c0c0c0ff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_55.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_2_2.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_3_1.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_4_1.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_5.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_6.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_7.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_8.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_9.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_10.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_11.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_12.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_13.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_14.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_15.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_16.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_17.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_18.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_19.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_20.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_21.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_22.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_23.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_24.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_25.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_26.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_27.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_28.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_29.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_30.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_31.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_32.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_33.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_34.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_35.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_36.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_37.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_38.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_39.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_40.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_41.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_42.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_43.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_44.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_45.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_46.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_47.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_48.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_49.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_50.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_51.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_52.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_53.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_54.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_56.geometry} material={materials.Standard_6} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_57.geometry} material={materials.Standard} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_2_3.geometry} material={materials.Standard} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_58.geometry} material={materials.Standard_1} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_59.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_60.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_2_4.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_61.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_2_5.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_62.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_2_6.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_3_2.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_63.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_64.geometry} material={materials.Standard_1} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_2_7.geometry} material={materials.Standard_1} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_3_3.geometry} material={materials.Standard_1} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_4_2.geometry} material={materials.Standard_1} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_5_1.geometry} material={materials.Standard_1} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_6_1.geometry} material={materials.Standard_1} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_7_1.geometry} material={materials.Standard_1} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_65.geometry} material={materials.Standard} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_66.geometry} material={materials['Color #404040ff']} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_100.geometry} material={materials['Color #c0c0c0ff']} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_100_1.geometry} material={materials['Color #808080ff']} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_100_2.geometry} material={materials['Color #ffff00ff']} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_100_3.geometry} material={materials['Color #ffffffff']} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_101.geometry} material={materials['Color #c0c0c0ff']} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_101_1.geometry} material={materials['Color #808080ff']} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_101_2.geometry} material={materials['Color #ffff00ff']} />
          <mesh castShadow receiveShadow geometry={nodes.mesh_101_3.geometry} material={materials['Color #ffffffff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_68.geometry} material={materials['Color #404040ff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_69.geometry} material={materials['Color #404040ff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_70.geometry} material={materials['Color #404040ff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_71.geometry} material={materials.Standard_2} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_72.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_73.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_2_9.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes['<Chassis_-_Lift_Arm_Mounting_Panel>-<Cut-Extrude101>'].geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes['<Chassis_-_Main_Side_Panel>-<Fillet5>'].geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes['<Chassis_-_Main_Side_Panel>-<Cut-Extrude6>'].geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_74.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_75.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_76.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_77.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_78.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_79.geometry} material={materials['Color #cad1eeff']} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_80.geometry} material={materials['Color #cad1eeff']} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_81.geometry} material={materials['Color #cad1eeff']} position={[0, 0, -2133.6]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_82.geometry} material={materials['Color #cad1eeff']} position={[0, 0, -2997.2]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_83.geometry} material={materials['Color #cad1eeff']} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_84.geometry} material={materials['Color #cad1eeff']} position={[0, 0, -2151.14]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_85.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_2_10.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_86.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_2_11.geometry} material={materials['Color #cad1eeff']} />
        </group>}
      {parts['Loader_Lift_Arm_Assembly-1'] &&
        <group position={[0, 0.35, 0]} scale={0.001} ref={groupRefs.current['Loader_Lift_Arm_Assembly-1']}>
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_87.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_88.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_89.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_90.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_2_12.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_91.geometry} material={materials.Standard_1} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_2_13.geometry} material={materials.Standard_1} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_3_4.geometry} material={materials.Standard_1} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_4_3.geometry} material={materials.Standard_1} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_92.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_93.geometry} material={materials.Standard_2} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_94.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_95.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_96.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_97.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_98.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_99.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_100.geometry} material={materials['Color #cad1eeff']} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes['<Lift_Arm_-_Base_Frame>-<Cut-Extrude11>'].geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes['<Lift_Arm_-_Outer_Frame>-<Fillet6>'].geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes['<Rear_Dog_Leg_Linkage>-<Mirror1>'].geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes['<Lift_Arm_-_Hydraulic_Cylinder_Attachment_Bracket>-<Mirror2>'].geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes['<Lift_Arm_-_Hydraulic_Cylinder_Attachment_Bracket>-<Fillet1>'].geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes['<Hydraulic_Cylinder>-<Combine1>'].geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes['<Lift_Arm_-_Hydraulic_Cylinder_Saddle>-<Boss-Extrude2>'].geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes['<Lift_Arm_-_Inter_Frame>-<Boss-Extrude1>'].geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes['<Bucket_Control_-_Hydraulic_Cylinder>-<Cut-Extrude5>'].geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes['<Lift_Arm_-_Limit_Linkage_Saddle>-<Fillet5>'].geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes['<Hydaulic_Cylinder_-_Mounting_Pin>-<CirPattern1>'].geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes['<Rear_Dog_Leg_Linkage_-_Mounting_Bolt>-<CirPattern1>'].geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes['<Bucket_Control_-_Hydaulic_Cylinder_Saddle>-<Cut-Extrude21>'].geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_101.geometry} material={materials['Color #cad1eeff']} position={[0, 0, -2133.6]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_102.geometry} material={materials.Standard_1} />
          <mesh castShadow receiveShadow geometry={nodes['<Lift_Arm_-_Limit_Linkage>-<Chamfer3>'].geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes['<Lift_Arm_-_Limit_Linkage>-<Chamfer2>'].geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes['<Lift_Arm_-_Limit_Linkage>-<Chamfer1>'].geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_103.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_2_14.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes['<Main_Lift_Hydraulic_-_Arm_Connection_Pin>-<Mirror1>'].geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes['<Main_Lift_Hydraulic_-_Arm_Connection_Pin>-<Revolve1>'].geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_104.geometry} material={materials.Standard_1} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_105.geometry} material={materials.Standard_1} position={[0, 18.02, 0]} rotation={[0, 0, -Math.PI]} scale={0.04} />
        </group>}
      {parts['Bucket_Assembly-1'] &&
        <group position={[0, 0.35, 0]} scale={0.001} ref={groupRefs.current['Bucket_Assembly-1']}>
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_106.geometry} material={materials.Standard_4} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_2_15.geometry} material={materials.Standard_4} position={[213.78, 0, 0]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_3_5.geometry} material={materials.Standard_4} position={[427.57, 0, 0]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_4_4.geometry} material={materials.Standard_4} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_5_2.geometry} material={materials.Standard_4} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_6_2.geometry} material={materials.Standard_4} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_7_2.geometry} material={materials.Standard_4} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_8_1.geometry} material={materials['AISI 4130 Steel, normalized at 870C']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_9_1.geometry} material={materials.Standard_4} material-color={partColors['Bucket_Assembly-1']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_10_1.geometry} material={materials.Standard_4} material-color={partColors['Bucket_Assembly-1']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_11_1.geometry} material={materials.Standard_4} material-color={partColors['Bucket_Assembly-1']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_12_1.geometry} material={materials.Standard_4} material-color={partColors['Bucket_Assembly-1']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_13_1.geometry} material={materials.Standard_4} material-color={partColors['Bucket_Assembly-1']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_14_1.geometry} material={materials.Standard_4} material-color={partColors['Bucket_Assembly-1']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_107.geometry} material={materials.Standard_5} material-color={partColors['Bucket_Assembly-1']} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_108.geometry} material={materials.Standard_5} material-color={partColors['Bucket_Assembly-1']} position={[-213.78, 0, 0]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_109.geometry} material={materials.Standard_5} material-color={partColors['Bucket_Assembly-1']} position={[-427.57, 0, 0]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_110.geometry} material={materials.Standard_5} material-color={partColors['Bucket_Assembly-1']} position={[-641.35, 0, 0]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_111.geometry} material={materials.Standard_5} material-color={partColors['Bucket_Assembly-1']} position={[-855.13, 0, 0]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_112.geometry} material={materials.Standard_5} material-color={partColors['Bucket_Assembly-1']} position={[-1068.92, 0, 0]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_113.geometry} material={materials.Standard_5} material-color={partColors['Bucket_Assembly-1']} position={[-1282.7, 0, 0]} scale={0.04} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_114.geometry} material={materials.Standard_1} material-color={partColors['Bucket_Assembly-1']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_2_16.geometry} material={materials.Standard_1} material-color={partColors['Bucket_Assembly-1']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_3_6.geometry} material={materials.Standard_1} material-color={partColors['Bucket_Assembly-1']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_140.geometry} material={materials.Standard_6} material-color={partColors['Bucket_Assembly-1']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_141.geometry} material={materials['AISI 4130 Steel, normalized at 870C']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_115.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_2_17.geometry} material={materials['Color #cad1eeff']} />
        </group>}
      {parts['Attachment_Coupler_Assembly-1'] &&
        <mesh castShadow receiveShadow geometry={nodes.BRep_1_116.geometry} material={materials['Color #cad1eeff']} position={[0, 0.35, 0]} scale={0.001} ref={groupRefs.current['Attachment_Coupler_Assembly-1']} />}
      {parts['Driver_Compartment_Assembly-1'] &&
        <group position={[0, 0.35, 0]} scale={0.001} ref={groupRefs.current['Driver_Compartment_Assembly-1']}>
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_117.geometry} material={materials.Standard_1} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_118.geometry} material={materials['Color #fcbc84ff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_119.geometry} material={materials.Standard_3} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_120.geometry} material={materials['Color #404040ff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_2_18.geometry} material={materials['Color #404040ff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_3_7.geometry} material={materials['Color #404040ff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_4_5.geometry} material={materials['Color #404040ff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_121.geometry} material={materials['Color #c0c0c0ff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_2_19.geometry} material={materials['Color #c0c0c0ff']} />
        </group>}
      {parts['Engine_Compartment_Assembly-2'] &&
        <group position={[0, 0.35, 0]} scale={0.001} ref={groupRefs.current['Engine_Compartment_Assembly-2']}>
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_122.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_123.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_2_20.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_124.geometry} material={materials['Color #00c0c0ff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_125.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_126.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_127.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_128.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_129.geometry} material={materials.Standard_1} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_130.geometry} material={materials.Standard_1} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_2_21.geometry} material={materials.Standard_1} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_131.geometry} material={materials.Standard_1} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_2_22.geometry} material={materials.Standard_1} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_3_8.geometry} material={materials.Standard_1} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_4_6.geometry} material={materials.Standard_1} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_5_3.geometry} material={materials.Standard_1} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_6_3.geometry} material={materials.Standard_1} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_7_3.geometry} material={materials.Standard_1} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_8_2.geometry} material={materials.Standard_1} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_9_2.geometry} material={materials.Standard_1} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_132.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_2_23.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_133.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_134.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_135.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_136.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_137.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_2_24.geometry} material={materials['Color #cad1eeff']} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_138.geometry} material={materials.Standard_1} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_1_139.geometry} material={materials.Standard_1} />
          <mesh castShadow receiveShadow geometry={nodes.BRep_2_25.geometry} material={materials.Standard_1} />
        </group>}
    </group>
  )
}

